In [1]:
import pandas as pd

# Load the processed electricity price datasets
train_df = pd.read_csv('train_with_monthly_gas.csv')

# Load the gas price dataset (monthly data)
gas_monthly_df = pd.read_csv('gas_2019.csv')  # Replace with the actual file path
gas_monthly_df = gas_monthly_df.rename(columns={"Month": "month", "Gas (NCG, THE)": "gas_price"})

# Add a year column to the gas data
gas_monthly_df['year'] = 2019  # Replace with the corresponding year for each file

# Create a 'date' column representing the first day of each month
gas_monthly_df['date'] = pd.to_datetime(gas_monthly_df[['year', 'month']].assign(day=1))

# Create a temporary 'date' column in the electricity dataset
train_df['date'] = pd.to_datetime(train_df['ds']).dt.to_period('M').dt.to_timestamp()

In [2]:
gas_monthly_df.head()

   month  gas_price  year       date
0      1     18.804  2018 2018-01-01
1      2     20.410  2018 2018-02-01
2      3     23.882  2018 2018-03-01
3      4     19.519  2018 2018-04-01
4      5     21.553  2018 2018-05-01

In [3]:
train_df.head(100)

,ds,y,unique_id,day_of_week,month,hour,is_weekend,is_holiday,month_sin,month_cos,day_of_week_sin,day_of_week_cos,hour_sin,hour_cos,date
0,2018-10-01 00:00:00,59.53,electricity_prices,0,10,0,0,0,-0.866025,0.5,0.000000,1.000000,0.000000,1.000000,2018-10-01
1,2018-10-01 01:00:00,56.10,electricity_prices,0,10,1,0,0,-0.866025,0.5,0.000000,1.000000,0.258819,0.965926,2018-10-01
2,2018-10-01 02:00:00,51.41,electricity_prices,0,10,2,0,0,-0.866025,0.5,0.000000,1.000000,0.500000,0.866025,2018-10-01
3,2018-10-01 03:00:00,47.38,electricity_prices,0,10,3,0,0,-0.866025,0.5,0.000000,1.000000,0.707107,0.707107,2018-10-01
4,2018-10-01 04:00:00,47.59,electricity_prices,0,10,4,0,0,-0.866025,0.5,0.000000,1.000000,0.866025,0.500000,2018-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018-10-04 23:00:00,52.25,electricity_prices,3,10,23,0,0,-0.866025,0.5,0.433884,-0.900969,-0.258819,0.965926,2018-10-01
96,2018-10-05 00:00:00,49.57,electricity_prices,4,10,0,0,0,-0.866025,0.5,-0.433884,-0.900969,0.000000,1.000000,2018-10-01
97,2018-10-05 01:00:00,51.16,electricity_prices,4,10,1,0,0,-0.866025,0.5,-0.433884,-0.900969,0.258819,0.965926,2018-10-01
98,2018-10-05 02:00:00,48.91,electricity_prices,4,10,2,0,0,-0.866025,0.5,-0.433884,-0.900969,0.500000,0.866025,2018-10-01
99,2018-10-05 03:00:00,47.36,electricity_prices,4,10,3,0,0,-0.866025,0.5,-0.433884,-0.900969,0.707107,0.707107,2018-10-01

In [4]:
# Merge gas prices into the electricity dataset
train_df = pd.merge(train_df, gas_monthly_df[['date', 'gas_price']], how='left', on='date')

# Drop the temporary 'date' column (it was only used for merging)
train_df = train_df.drop(columns=['date'])

# Save the updated training dataset
train_df.to_csv('train_with_monthly_gas_till_2019.csv', index=False)

print("Monthly gas prices successfully added to the training dataset.")

Monthly gas prices successfully added to the training dataset.